
# to comply with the tested version (at 24/12/2023):
# FROM pytorch@sha256:3387e598cb94fc248d82e712a65b10931a990cea3a2e76362ca30d135f565de4
FROM pytorch/pytorch:latest

# prevent apt from hanging
ARG DEBIAN_FRONTEND=noninteractive

ENV HOME /home

WORKDIR $HOME

# dependency: lang-segment-anything
RUN apt update
RUN apt install -y git
RUN apt install libgl1-mesa-glx -y
RUN apt install libglib2.0-0 -y
RUN git clone https://github.com/kauevestena/lang-segment-anything.git
WORKDIR $HOME/lang-segment-anything
RUN pip install -r requirements.txt
RUN python running_test.py

# this repository stuff:
WORKDIR $HOME
RUN git clone https://github.com/kauevestena/deep_pavements.git
WORKDIR $HOME/deep_pavements
RUN pip install -r requirements.txt
COPY mapillary_token mapillary_token



